// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiP6RE6DKS4VzDTiKpmG-wpFtof5W8yq0',
    appId: '1:95255877348:android:3d1af6481de9680d763ef1',
    messagingSenderId: '95255877348',
    projectId: 'lessons-945e0',
    databaseURL: 'https://lessons-945e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lessons-945e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TORD0OrSlxho_je7uy1ip92qhZhPj2M',
    appId: '1:95255877348:ios:65bb8a889f69e070763ef1',
    messagingSenderId: '95255877348',
    projectId: 'lessons-945e0',
    databaseURL: 'https://lessons-945e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lessons-945e0.appspot.com',
    iosClientId: '95255877348-528bovoannt8dbdjqflbtuqhiuh0qhcq.apps.googleusercontent.com',
    iosBundleId: 'uz.sokhib.lesson13',
  );
}
